### ISSUE TITLE
User Story: User Signup

### ISSUE THREAD

**Issue by dkustarnikov** [dkustarnikov/WorkoutWager#1]
---
name: User Story
about: Template for creating user stories
title: 'User Signup'
labels: user story
assignees: ''

---

## User Story

**As a** new user,
**I want to** sign up with my email and password,
**so that** I can create an account.

## Acceptance Criteria

- [ ] **Given** the sign-up page,
      **when** I enter a valid email and password,
      **then** I should be able to create an account and receive a confirmation response.

## Tasks

- [ ] Create `signupLambda` function.
- [ ] Integrate `signupLambda` with `POST /signup` endpoint.
- [ ] Add validation for email and password.
- [ ] Hash the password and store user data in DynamoDB.
- [ ] Write unit tests for the signup functionality.

## Notes

- Ensure password meets security criteria (e.g., minimum length, complexity).
