### ISSUE TITLE
User Story: User Login

### ISSUE THREAD

**Issue by dkustarnikov** [dkustarnikov/WorkoutWager#2]
---
name: User Story
about: Template for creating user stories
title: 'User Login'
labels: user story
assignees: ''

---

## User Story

**As a** user,
**I want to** log in with my email and password,
**so that** I can access my account.

## Acceptance Criteria

- [ ] **Given** the login page,
      **when** I enter a valid email and password,
      **then** I should receive a JWT token for authentication.

## Tasks

- [ ] Create `loginLambda` function.
- [ ] Integrate `loginLambda` with `POST /login` endpoint.
- [ ] Validate email and password.
- [ ] Verify password and generate JWT token.
- [ ] Write unit tests for the login functionality.

## Notes

- Ensure token is securely generated and stored.
