### ISSUE TITLE
US-003: Get User Information Endpoint

### ISSUE THREAD

**Issue by dkustarnikov** [dkustarnikov/WorkoutWager#4]
---
name: User Story
about: Template for creating user stories
title: 'Setup Endpoint to Retrieve User Information'
labels: user story
assignees: ''

---

## User Story

**As a** developer,
**I want to** set up an endpoint that retrieves specific user information based on userId or email,
**so that** I can provide a service to return user details.

## Acceptance Criteria

- [x] **Given** an authenticated user,
      **when** the user sends a request with either userId or email in the request body to the endpoint,
      **then** the system should return the corresponding user information (userId, username, and email).

## Tasks

- [x] Setup the endpoint using API Gateway
- [x] Create a Lambda function to handle the request and query the Cognito User Pool
- [x] Add a policy to the Lambda function allowing it to access Cognito and retrieve user information
- [x] Test the endpoint to ensure it correctly retrieves user information based on userId or email

## Notes

- Ensure the Lambda function handles both userId and email queries.
- Verify that the correct permissions are set for the Lambda function to access Cognito.
- Use Bruno or Postman to test the endpoint by sending requests with valid userId or email.
- Log relevant information in CloudWatch for debugging and verification.
